Use the REST API for Telemetry
travisghansen/hass-opnsense pull request #147
Opened 2024-08-31 04:03 UTC by Snuffy2

# Still in draft as I try to get as many of the same variables as the prior XMLRPC script

Requires adding additional permissions to the Home Assistant user in Opnsense. Exact permissions TBD.

2024-09-02 03:09 UTC, alexdelprete commented
@Snuffy2 I wanted to test it. But I have the following warnings/errors on HA restart:

![image](https://github.com/user-attachments/assets/77021606-93fd-4bf7-b349-24957621889a)

![image](https://github.com/user-attachments/assets/0a3e2cc5-7ef0-4364-a3ef-0b15dd928680)

And this one is preventing the integration to initialize:

```console
Logger: custom_components.opnsense
Source: helpers/update_coordinator.py:354
integration: OPNsense ([documentation](https://github.com/travisghansen/hass-opnsense), [issues](https://github.com/travisghansen/hass-opnsense/issues))
First occurred: 04:59:03 (6 occurrences)
Last logged: 05:01:15

Unexpected error fetching OPNsense OPNsense state data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 271, in _async_update_data
    return await self.update_method()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 97, in async_update_data
    await hass.async_add_executor_job(lambda: data.update())
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 97, in <lambda>
    await hass.async_add_executor_job(lambda: data.update())
                                              ^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 316, in update
    self._state["telemetry"] = self._get_telemetry()
                               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 225, in inner
    response = func(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/__init__.py", line 249, in _get_telemetry
    return self._client.get_telemetry()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 103, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 100, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 867, in get_telemetry
    telemetry["openvpn"] = self._get_telemetry_openvpn()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 103, in inner
    raise err
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 100, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/opnsense/pyopnsense/__init__.py", line 1016, in _get_telemetry_openvpn
    for vpnid, vpn_info in openvpn_info.items():
                           ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'items'
```

2024-09-02 03:25 UTC, alexdelprete commented
This is from the debug log:

```log
2024-09-02 05:01:27.035 DEBUG (SyncWorker_18) [custom_components.opnsense.pyopnsense] [get_telemetry_openvpn] openvpn_info: []
2024-09-02 05:01:27.035 DEBUG (SyncWorker_18) [custom_components.opnsense.pyopnsense] [get_telemetry_openvpn] connection_info: {'total': 0, 'rowCount': 0, 'current': 1, 'rows': []}
2024-09-02 05:01:27.035 ERROR (SyncWorker_18) [custom_components.opnsense.pyopnsense] Unexpected _get_telemetry_openvpn error err=AttributeError("'list' object has no attribute 'items'"), type(err)=<class 'AttributeError'>
2024-09-02 05:01:27.035 ERROR (SyncWorker_18) [custom_components.opnsense.pyopnsense] Unexpected get_telemetry error err=AttributeError("'list' object has no attribute 'items'"), type(err)=<class 'AttributeError'>
2024-09-02 05:01:27.035 ERROR (MainThread) [custom_components.opnsense] Unexpected error fetching OPNsense OPNsense state data
```

2024-09-02 03:52 UTC, alexdelprete requested changes
A couple of fixes, a minor one and the other was preventing the integration to start.

2024-09-02 03:52 UTC, alexdelprete commented on custom_components/opnsense/pyopnsense/__init__.py
> +        for vpnid, vpn_info in openvpn_info.items():
Added a check if `openvpn_info` list is empty. Happens when there's no OpenVPN interface (at least here), and it stops the integration from loading. I modified it like this and it works now.

```python
    @_log_errors
    def _get_telemetry_openvpn(self) -> dict:
        openvpn: dict[str, Any] = {}
        openvpn["servers"] = {}
        openvpn_info: dict[str, Any] = self._post("/api/openvpn/export/providers")
        connection_info: dict[str, Any] = self._post(
            "/api/openvpn/service/searchSessions"
        )
        _LOGGER.debug(f"[get_telemetry_openvpn] openvpn_info: {openvpn_info}")
        _LOGGER.debug(f"[get_telemetry_openvpn] connection_info: {connection_info}")
        if openvpn_info:
            for vpnid, vpn_info in openvpn_info.items():
                vpn: dict[str, Any] = {}
                vpn["vpnid"] = vpn_info["vpnid"]
                vpn["name"] = vpn_info["name"]
                total_bytes_recv = 0
                total_bytes_sent = 0
                for connect in connection_info["rows"]:
                    if connect["id"] == vpn["vpnid"]:
                        total_bytes_recv += (
                            int(connect["bytes_received"])
                            if connect["bytes_received"]
                            else 0
                        )
                        total_bytes_sent += (
                            int(connect["bytes_sent"]) if connect["bytes_sent"] else 0
                        )
                vpn["total_bytes_recv"] = total_bytes_recv
                vpn["total_bytes_sent"] = total_bytes_sent
                # Missing connected_client_count
                # vpn["connected_client_count"] =
                openvpn["servers"][vpnid] = vpn
            _LOGGER.debug(f"[get_telemetry_openvpn] openvpn: {openvpn}")
        else:
            _LOGGER.debug("[get_telemetry_openvpn] openvpn_info: no OpenVPN interfaces")
        return openvpn
```

2024-09-02 03:52 UTC, alexdelprete commented on custom_components/opnsense/pyopnsense/__init__.py
> +            filesystem["capacity"] = f"{filesystem.pop("used_pct")}%"
I had an issue with VSCode giving me weird errors for this line, had to modify with single quotes:

```python
filesystem["capacity"] = f"{filesystem.pop('used_pct')}%"
```

2024-09-02 21:12 UTC, Snuffy2 commented
Sorry, lazy coding on my part. Added more robust error handling that hopefully handles most/all potential issues with the data.

2024-09-02 21:56 UTC, alexdelprete commented
> I'm seeing this Warning too. Not sure it has anything to do with the code changes in this PR though.
> 
> ![](https://private-user-images.githubusercontent.com/7027842/363548611-77021606-93fd-4bf7-b349-24957621889a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUzMTE4MTksIm5iZiI6MTcyNTMxMTUxOSwicGF0aCI6Ii83MDI3ODQyLzM2MzU0ODYxMS03NzAyMTYwNi05M2ZkLTRiZjctYjM0OS0yNDk1NzYyMTg4OWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkwMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MDJUMjExMTU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWE5YmU0ZGY2NTEwMmI3MDVjMjA4MzhjODM3ZmFiMjg0OGQ1ZjQ0NzQxY2YxZjRjOTFhZmQyNzIxYzNjMGExYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EYXDYgpeK1uHeDWDebrKGC1BtdoRXBbzEtIWh8GHm9U)

Well, the log is pretty clear, it also mentions the lines: it's always the code `script = """`

![image](https://github.com/user-attachments/assets/45890134-eae4-48f6-b08e-862934284718)

2024-09-02 22:06 UTC, alexdelprete commented
> Sorry, lazy coding on my part. Added more robust error handling that hopefully handles most/all potential issues with the data.

Thank you very much for your contribution. I'll try to understand better how it works so I might be of help in the future. Hope we'll be able to use the REST API for everything in the future. :)

2024-09-02 22:09 UTC, Snuffy2 commented
I added a commit to handle the Warnings with the PHP scripts. I don't believe they are appearing from any of the code changes in this PR. Instead, I suspect they're now showing due to Python updates in HA 2024.8 . However, making the scripts raw strings should fix it.

2024-09-02 22:12 UTC, alexdelprete commented
> I don't believe they are appearing from any of the code changes in this PR

I agree, it's not due to this PR. Sorry if I wrongly attributed those to it and thanks for fixing it, I just tested it and the warning has gone. :)

2024-09-02 22:14 UTC, alexdelprete commented
@Snuffy2 the only problem I noticed with this PR is that the interface entities names have changed, instead of wan/lan/optX/etc. now there's the custom name of the interface. It makes sense, but this will require users to do some cleanup work in HA, removing orphan entities with the old names.

2024-09-02 22:23 UTC, Snuffy2 commented
Yes, it is using the Name instead of the device now. I could change that back if desired but I thought it was more useful with the friendly name. 

Similarly the OpenVPN Server names are now also different because I'm pulling from the new OpenVPN interface and not the legacy one. I can't change that one.

2024-09-02 22:44 UTC, alexdelprete commented
> Yes, it is using the Name instead of the device now. I could change that back if desired but I thought it was more useful with the friendly name.

I would use Name as Friendly Name in HA, and Device for the name of the entity. But that's just my humble opinion, let's see what @travisghansen says about this.

> Similarly the OpenVPN Server names are now also different because I'm pulling from the new OpenVPN interface and not the legacy one. I can't change that one.

Obviously we can't do much about that, users will have to adapt.

2024-09-04 01:35 UTC, travisghansen commented
Thanks everyone! I am happy to merge this or even better get some additional people added as maintainers on the repo given my limited time.

2024-09-04 02:14 UTC, alexdelprete commented
> I am happy to merge this or even better get some additional people added as maintainers on the repo given my limited time.

I'm not an expert developer Travis, but I'd be happy to help as I can. Would be awesome if @Snuffy2 could join the team of maintainers. :)

2024-09-04 11:55 UTC, merged

2024-09-04 12:08 UTC, alexdelprete commented
> Yes, it is using the Name instead of the device now. I could change that back if desired but I thought it was more useful with t

I had a chat with Travis, and he agreed with me that it's better changing it back. Do you want to prepare a new PR? Otherwise I'll look at the code and prepare it later. Let me know...

2024-09-04 20:47 UTC, Snuffy2 commented
@travisghansen, if you don't mind me moving things that I fix or update from XMLRPC/PHP to the REST API using pure Python then I'm happy to help to maintain. Feel free to contact me at github@mail.snuffy2.com if you'd like to contact me outside of GitHub.

As for the interface naming, since v0.1.22 is released and anyone who upgrades to it will get new HA entities, wont it be more confusing to release another update that changes the interface name and IDs again?

2024-09-04 20:52 UTC, travisghansen commented
I am happy to let people take the project wherever it needs to go (regarding rest vs xmlrpc).

I think if we’re fast enough it’s fine to catch the id change. Not everyone updates their installs everyday..so a same day release for example to ‘fix’ that issue I think is fine.

2024-09-04 21:57 UTC, alexdelprete commented
> I am happy to let people take the project wherever it needs to go (regarding rest vs xmlrpc)

Travis, remember when we asked Franco (OPNsense lead dev) about XMLrpc vs API when we started this adventure? He said eventually XMLrpc will be abandoned in favor of the API, once OPNsense GUI will only use the API.

So I guess the API transition is inevitable. I don't know if the API covers everything that we got via XMLrpc though.

Happy to see that @Snuffy2 accepted to maintain this project. :)

2024-09-04 21:59 UTC, alexdelprete commented
Regarding the interface naming: I would use device for the name of entities, and the user description as HA friendly name for the entity. What do you think @Snuffy2?

2024-09-04 22:09 UTC, travisghansen commented
xmlrpc was always a temporary solution until the rest api reached parity…when originally built (and likely still) the rest api was limited enough that the whole plugin would be pretty useless, but transitioning as the rest api allows is definitely preferred.

2024-09-04 22:36 UTC, alexdelprete commented
and once the API is complete, we can also get rid of the required opnsense plugin.

2024-09-05 02:44 UTC, travisghansen commented
Yes that is true.

2024-09-10 22:46 UTC, alexdelprete commented
> Feel free to contact me at [github@mail.snuffy2.com](mailto:github@mail.snuffy2.com) if you'd like to contact me outside of GitHub.

Snuffy, in agreement with Travis, we created a Discord server to have a more direct communication channel. I put the link in the readme (the discord badge) if you want to join. :)

Thanks for everything you're doing for this integration.